# All settings related to language and the content of messages will be in this file.
# Currently supported languages:
#  • English (en)
#  • Español (es)
#  • Íslenska (is)
#  • Magyar (hu)
#  • Polskie (pl)
# Note: You MUST type the letters in the parentheses
language: 'en'

# - - - - - - - - - - -
# ~ MESSAGE OVERRIDES ~
# All non-error messages sent by the plugin will appear in the `lang_en` file (and eventually in all other language
#   files as well), and any message that is stored in the language file can be overridden here. To override a message,
#   just add the existing key of the message from the original language file, and set the value to whatever message you
#   would like. A list of all messages can be found here:
#   https://github.com/donvi-bz/JakesRTP/blob/master/Core/src/main/resources/translations/lang_en.yml
# Notes on formatting:
#   To make a line break, type this: \n
#   To use a legacy color code, place an `&` in front of a hex digit (0-9|a-f) like this: &8
#   You can use full hex codes (if you are in the right version of minecraft) like this: {#00FFC8}
# Finally, if you know another language and would like to help translate this plugin, you can copy the `lang_en.yml`
#   file found here https://github.com/donvi-bz/JakesRTP/tree/master/Core/src/main/resources/translations then
#   translate the new language and make a PR. Or you could send me the file another way. Either way, if you do this,
#   thank you so much. ♥

need-to-wait-for-cooldown: 'Whoops! You still have to wait {0}'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# ~ LIST OF ALL CUSTOMIZABLE DEFAULT TRANSLATIONS ~
# You can uncomment and customize any of the following messages:
#
# not-permitted-generic: 'Could not RTP for reason: {0}'
# not-permitted-major-error: 'Error. Could not RTP for reason: {0} \nPlease check console for more info on why teleportation failed.'
# not-enabled-in-this-world: 'RTP is not enabled in this world. {0}'
# no-settings-found-with-name: 'No RTP settings found with name {0}'
# no-settings-found-with-name-for-player: 'No RTP settings found with name {0}'
# too-many-failed-attempts: 'Too many failed attempts.'
# player-not-found: 'Could not find player {0}'
# world-not-found: 'Could not find world {0}'
# rtp-settings-no-contain-world: 'Input mismatch: RtpSettings "{0}" does not contain the world "{1}" as one of its enabled worlds.'
# rtp-settings-must-use-world: 'Input mismatch: RtpSettings "{0}" can only teleport people in world "{1}"'
# teleporting-in-x-seconds: 'Teleporting in {0} seconds...'
# moved-during-warmup: 'Movement detected, RTP Canceled.'
# rtp-called-while-in-warmup: 'You are already waiting on an RTP warmup!'
# not-enough-money: 'You do not have enough money for this. Cost: {0}. Balance: {1}.'
# no-longer-enough-money: 'You no longer have the required funds to do this.'
# you-were-charged-x: 'You were charged {0} and now have {1}'
# economy-error: 'An economy error occurred: {0}'
# readable-time: '{0}{1}{2}{3}'
# readable-time-word-days:    '{0} days, '
# readable-time-word-hours:   '{0} hours, '
# readable-time-word-minutes: '{0} minutes, '
# readable-time-word-seconds: '{0} seconds.'
